from datetime import datetime
from pathlib import Path
from typing import Dict, Any


def generate_markdown_report(data: Dict[str, Any], output_dir: Path) -> Path:
    """
    Generate a Markdown report from recon data.
    """
    domain = data.get("target", "unknown")
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%SZ")

    safe_domain = domain.replace(".", "_")
    report_path = output_dir / f"recon-{safe_domain}.md"

    lines: list[str] = []

    # -----------------------------------------------------------------
    # Header
    # -----------------------------------------------------------------
    lines.append(f"# Reconnaissance Report — `{domain}`")
    lines.append("")
    lines.append(f"- **Generated at:** {timestamp}")
    lines.append("")

    # -----------------------------------------------------------------
    # Summary
    # -----------------------------------------------------------------
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Subdomains discovered:** {len(data.get('subdomains', []))}")
    lines.append(f"- **Technologies detected:** {', '.join(data.get('technologies', [])) or 'None'}")
    lines.append("")

    # -----------------------------------------------------------------
    # Domain Info
    # -----------------------------------------------------------------
    domain_info = data.get("domain", {})
    lines.append("## Domain Information")
    lines.append("")
    lines.append(f"- **IP Address:** {domain_info.get('ip')}")
    lines.append(f"- **ASN:** {domain_info.get('asn', {}).get('asn')}")
    lines.append(f"- **ASN Description:** {domain_info.get('asn', {}).get('asn_description')}")
    lines.append("")

    # -----------------------------------------------------------------
    # DNS
    # -----------------------------------------------------------------
    lines.append("## DNS Records")
    lines.append("")
    dns_info = data.get("dns", {}).get("records", {})
    for record_type, values in dns_info.items():
        lines.append(f"### {record_type}")
        for v in values:
            lines.append(f"- {v}")
        if not values:
            lines.append("- (none)")
        lines.append("")

    # -----------------------------------------------------------------
    # Subdomains
    # -----------------------------------------------------------------
    lines.append("## Subdomains")
    lines.append("")

    passive = data.get("passive_subdomains", [])
    active = data.get("subdomains", [])

    if passive:
        lines.append("### Passive Subdomains")
        for s in passive:
            lines.append(f"- {s}")
        lines.append("")

    if active:
        lines.append("### Active Subdomains")
        for s in active:
            lines.append(f"- {s}")
        lines.append("")

    # -----------------------------------------------------------------
    # HTTP & Technologies
    # -----------------------------------------------------------------
    lines.append("## Web & Technologies")
    lines.append("")
    lines.append(f"- **Reachable:** {data.get('http', {}).get('reachable')}")
    lines.append(f"- **HTTP Status:** {data.get('http', {}).get('status_code')}")
    lines.append(f"- **Technologies:** {', '.join(data.get('technologies', [])) or 'None'}")
    lines.append("")

    # -----------------------------------------------------------------
    # Shodan
    # -----------------------------------------------------------------
    shodan = data.get("shodan", {})
    if shodan.get("found"):
        lines.append("## Shodan Intelligence")
        lines.append("")
        lines.append(f"- **Organization:** {shodan.get('data', {}).get('organization')}")
        lines.append(f"- **ISP:** {shodan.get('data', {}).get('isp')}")
        lines.append(f"- **Country:** {shodan.get('data', {}).get('country')}")
        lines.append(f"- **Open Ports:** {shodan.get('data', {}).get('ports')}")
        lines.append("")

    # -----------------------------------------------------------------
    # Footer
    # -----------------------------------------------------------------
    lines.append("---")
    lines.append("_Generated by recon-tool_")

    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path
